name       : unzip
version    : '6.0'
release    : 8
source     :
    - https://jaist.dl.sourceforge.net/project/infozip/UnZip%206.x%20%28latest%29/UnZip%206.0/unzip60.tar.gz : 036d96991646d0449ed0aa952e4fbe21b476ce994abc276e49d30e686708bd37
homepage   : http://www.info-zip.org/UnZip.html
license    : Info-ZIP
summary    : Info-ZIP unzip program
component  : system.base
description: |
    Info-ZIP portable compression/archiver utilities (Zip, UnZip, WiZ, etc.)
setup      : |
    sed -i -e 's/CFLAGS=\"-O -Wall/& -DNO_LCHMOD/' unix/Makefile
    %apply_patches
build      : |
    %make -f unix/Makefile generic
install    : |
    %make_install prefix=$installdir/usr MANDIR=$installdir/usr/share/man/man1 -f unix/Makefile
