name        : unzip
version     : 6.0
release     : 5
source      :
    - http://downloads.sourceforge.net/infozip/unzip60.tar.gz : 036d96991646d0449ed0aa952e4fbe21b476ce994abc276e49d30e686708bd37
homepage    : http://sourceforge.net/projects/infozip/
license     :
    - Info-ZIP
summary     : Info-ZIP unzip program
component   : system.base
description : |
    Info-ZIP portable compression/archiver utilities (Zip, UnZip, WiZ, etc.)
setup      : |
    sed -i -e 's/CFLAGS=\"-O -Wall/& -DNO_LCHMOD/' unix/Makefile
    %patch -p1 < $pkgfiles/security/cve-2014-9636.patch
    %patch -p1 < $pkgfiles/security/cve-2014-9913.patch
    %patch -p1 < $pkgfiles/security/cve-2015-7696.patch
    %patch -p1 < $pkgfiles/security/cve-2015-7697.patch
    %patch -p1 < $pkgfiles/security/cve-2016-9844.patch

build      : |
    %make -f unix/Makefile linux_noasm
install    : |
    %make_install prefix=$installdir/usr
    mv $installdir/usr/man $installdir/usr/share
    install -Dm644 LICENSE $installdir/usr/share/doc/unzip/LICENSE
    install -Dm644 BUGS $installdir/usr/share/doc/unzip/BUGS
